### PR TITLE
[Bugfix] fixing the timer for interval

### LINKED ISSUE #80: issue testing page with moment-from-now
My acceptance tests stopped working in pages where I added the `moment-from-now` with an interval.

The tests start with `visit` to a url, followed by `andThen` containing the asserts.
Unfortunately the tests fail with a timeout and the `andThen` isn't called.

I'm guessing the problem is the endless `Ember.runLater` that the testing framework waiting for all the jobs queue to empty before activating the next `andThen`.

Without passing an interval to the moment-from-now the tests work as expected.

This issue isn't specific to ember-moment.  It was reported to Ember since 2013 and still is open - see https://github.com/emberjs/ember.js/issues/3008
@teddyzeenny provided a workaround in that thread, ie. instead of `runLater` use:
`setTimeout(function() { Em.run(function() { //.. code here } });`

### PR DESCRIPTION
**Pull request by jasonmit**
Fixes #80

/cc @stefanpenner

### CODE REVIEW

File: addon/helpers/moment-from-now.js [hunk 1]
```diff
@@ -17,7 +26,11 @@ export function helperFactory() {
           time = time.locale(hash.locale);
         }
         return time.fromNow(hash.hideSuffix);
-      })
+      }),
+      destroy() {
+        this.clearTimer();
+        return this._super.apply(this, arguments);
```
Comment (stefanpenner) [inline addon/helpers/moment-from-now.js]: dont think this return is needed

File: addon/helpers/moment-from-now.js [hunk 2]
```diff
@@ -2,14 +2,23 @@ import Ember from 'ember';
...
+          clearTimeout(this.timer);
+        }
+      },
       compute: computeFn(function(params, hash) {
+        this.clearTimer();
+
         if (hash.interval) {
-          runLater(this, this.recompute, parseInt(hash.interval, 10));
+          this.timer = setTimeout(() => {
+            emberRun(this, this.recompute);
```
Comment (stefanpenner) [inline addon/helpers/moment-from-now.js]: `Ember.run.bind` might be nice here

```js
setTimeout(Ember.run.bind(this, this.recompute), parseInt(hash.internal, 10))
```

File: addon/helpers/moment-from-now.js [hunk 3]
```diff
@@ -2,14 +2,23 @@ import Ember from 'ember';
...
 import computeFn from '../utils/compute-fn';
 
-const { later:runLater } = Ember.run;
+const emberRun = Ember.run;
 
 export function helperFactory() {
   if (Ember.Helper) {
     return Ember.Helper.extend({
+      clearTimer() {
+        if (this.timer) {
```
Comment (stefanpenner) [inline addon/helpers/moment-from-now.js]: this guard isn't needed.

File: addon/helpers/moment-to-now.js [hunk 4]
```diff
@@ -2,14 +2,22 @@ import Ember from 'ember';
...
 import computeFn from '../utils/compute-fn';
 
-const { later:runLater } = Ember.run;
+const emberRun = Ember.run;
 
 export function helperFactory() {
   if (Ember.Helper) {
     return Ember.Helper.extend({
+      clearTimer() {
+        if (this.timer) {
```
Comment (stefanpenner) [inline addon/helpers/moment-to-now.js]: ^^

File: addon/helpers/moment-to-now.js [hunk 5]
```diff
@@ -2,14 +2,22 @@ import Ember from 'ember';
...
+          clearTimeout(this.timer);
+        }
+      },
       compute: computeFn(function(params, hash) {
+        this.clearTimer();
         if (hash.interval) {
-          runLater(this, this.recompute, parseInt(hash.interval, 10));
+          this.timer = setTimeout(() => {
+            emberRun(this, this.recompute);
```
Comment (stefanpenner) [inline addon/helpers/moment-to-now.js]: ^^
